version: '3'
services:
  flask_app:
    build: ./backend/
    depends_on:
      - otel-collector
    labels:
      my.custom.label.team: 'dev'
    ports:
      - 5500:5500
  
  react_app:
    build: ./frontend/
    depends_on:
      - otel-collector
    labels:
      my.custom.label.team: 'dev'
    ports:
      - 3000:3000
      
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    command: [--config=/etc/otelcol-contrib/config.yaml]
    env_file:
      - ./otel-collector/.env.local
    volumes:
      - ./otel-collector/collector.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888 # pprof extension
      - 8888 # Prometheus metrics exposed by the collector
      - 8889 # Prometheus exporter metrics
      - 13133 # health_check extension
      - 4317 # OTLP grpc receiver
      - 55679 # zpages extension

